dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'

    // Security dependencies that might be needed for gateway
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // Redis for rate limiting
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'

    // Netty DNS resolver for MacOS
    runtimeOnly 'io.netty:netty-resolver-dns-native-macos:4.1.107.Final:osx-aarch_64'

    // Kafka dependencies
    implementation 'org.springframework.kafka:spring-kafka'

    // Common module dependency
    implementation project(':common')

    tasks.named('processResources') {
        from(project(':common').sourceSets.main.resources) {
            include '**/*.yml'
        }
    }
}
