name: Deploy DEV

on:
  push:
    branches: [ "develop" ]  # develop push trigger 시 실행
    # paths-ignore:
    #   - '.github/**'
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  detect-modules:
    name: Detect Changed Modules
    runs-on: ubuntu-latest
    # runs-on: [ dev-runner, self-hosted ]
    outputs:
      changed_json: ${{ steps.changed-mods.outputs.changed_json }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      # 모듈 내 소스파일 말고 루트 폴더에 있는 것들도 변경됐을때 배포되도록 해주어야하나 고민중
      - name: Determine changed files and modules
        id: changed-mods
        shell: bash
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.event.after }}"
          fi

          echo "BASE: $BASE_SHA"
          echo "HEAD: $HEAD_SHA"

          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          ALL_MODULES="auth-api gateway payment-api user-api"
          MODULES=""

          for m in $ALL_MODULES; do
            if echo "$CHANGED_FILES" | grep -q "$m/"; then
              MODULES="$MODULES $m"
            fi
          done

          if echo "$CHANGED_FILES" | grep -q "common/"; then
            MODULES="$ALL_MODULES"
          fi

          MODULES=$(echo $MODULES | xargs) # trim
          echo "Changed modules: $MODULES"
          
          json="["
            for m in $MODULES; do
              json="$json\"$m\","
            done
            json="${json%,}]"

            echo "JSON modules: $json"
            echo "changed_json=$json" >> $GITHUB_OUTPUT


  deploy:
    name: Build Changed Modules
    needs: detect-modules
    if: ${{ needs.detect-modules.outputs.changed_json != '' }}
    runs-on: ubuntu-latest
    # runs-on: [ dev-runner, self-hosted ]

    strategy:
      matrix:
        module: ${{ fromJson(needs.detect-modules.outputs.changed_json) }}

    steps:
      - name: Configure Git
        shell: 'bash'
        run: git config --global http.postBuffer 314572800  # 300MB로 설정

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get-version
        shell: 'bash'
        run: |
          echo "branch :: $GITHUB_REF_NAME"
          echo "sha :: ${GITHUB_SHA::10}"
          values_prefix=${INPUT_VALUES_PREFIX:-}
          APP_VERSION="$GITHUB_REF_NAME-${GITHUB_SHA::10}"
          APP_VERSION="${values_prefix:+${values_prefix}-}${APP_VERSION}"
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "APP_VERSION=${APP_VERSION}" # print

      - name: Build with Gradle
        shell: 'bash'
        run: |
          MODULE="${{ matrix.module }}"
          echo "Building module: $MODULE"

          GRADLE_CMD="./gradlew :$MODULE:build"

          if [ "${{ inputs.run-tests }}" == "false" ]; then
            GRADLE_CMD="$GRADLE_CMD -x test"
          fi

          GRADLE_CMD="$GRADLE_CMD --no-daemon --build-cache --project-cache-dir=/opt/hostedtoolcache/gradle_project_cache/${{ github.repository }}"
          echo "Running: $GRADLE_CMD"
          $GRADLE_CMD


      - name: Setup QEMU # 필요 없을거같기도 함
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Image
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/mallowlink-pay-${{ matrix.module }}:${{ env.APP_VERSION }}"
          
          echo "$IMAGE"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE \
            --build-arg MODULE=${{ matrix.module }} \
            --push \
            .

      - name: Checkout Target Repository
        if: success()
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/pay-test
          path: ${{ github.workspace }}/k8s-clone
          ref: main
      
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

    
      - name: Update Image Version in the related HelmChart values.yaml
        if: success()
        shell: 'bash'
        run: |
          MODULE="${{ matrix.module }}"
          REPO_PATH="${{ github.workspace }}/k8s-clone/charts/$MODULE"
          FILE="$REPO_PATH/values.dev.yaml"

          echo "$MODULE"
          echo "$REPO_PATH"
          echo "$FILE"

          KEY=".${MODULE}.image.tag"
          echo ${KEY}

          cat values.dev.yaml

# yq -i "$KEY = env(APP_VERSION)" "$FILE"
    

  #     -

# gradle build -> 아니 도커 빌드하는데에 다 들어가있지않나
# docker login
# docker build
# docker push -> 일단 개인 레포로 올라가는거까진 확인함
# 헬름 차트 불러와서 수정하는거까지 하면 될듯싶긴한디






